#
# Corne TP Settings
#

# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y


#
# Logging
#

CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_LOGGING_MINIMAL=y
CONFIG_PS2_LOG_LEVEL_DBG=n
CONFIG_UART_LOG_LEVEL_DBG=n
CONFIG_LOG_MODE_IMMEDIATE=n

# Enable for debugging (increases firmware size)
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000


#
# PS/2 Mouse / Trackpoint Driver Settings
#

# Enable compatibility with urob's zmk fork
# CONFIG_ZMK_INPUT_MOUSE_PS2_ENABLE_UROB_COMPAT=n

# Enable additional error mitigations (for GPIO driver)
# CONFIG_ZMK_INPUT_MOUSE_PS2_ENABLE_ERROR_MITIGATION=y

# Enable PS2 resend callback (requires custom zephyr)
# CONFIG_PS2_GPIO_ENABLE_PS2_RESEND_CALLBACK=y
# CONFIG_PS2_UART_ENABLE_PS2_RESEND_CALLBACK=y


#
# System Settings
#

# Save config to flash more frequently (for debugging only)
# Default is 60s
# CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE 10000

# Enable experimental BLE settings
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
