# Cradio Settings

# Uncomment for RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment for OLED display
# CONFIG_ZMK_DISPLAY=y

#
# Logging
#

# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_ZMK_LOGGING_MINIMAL=y

#
# System Settings
#

# Enable experimental BLE
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y